source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

# Our Libraries
def libraries
  pod 'Moya-ObjectMapper', :path => "../"
end

def libraries_rx_swift
  pod 'Moya-ObjectMapper/RxSwift', :path => "../"
  # pod 'Moya/RxSwift', '~> 13.0.1'
  pod 'RxSwift', '~> 5.0.0'
  pod 'RxDataSources', '~> 4.0.0'
  pod 'RxCocoa', '~> 5.0.0'
  pod 'RxAlertController', '~> 5.0.0'
end

def libraries_reactive_swift
  pod 'Moya-ObjectMapper/ReactiveSwift', :path => "../"
  pod 'Moya/ReactiveSwift', '~> 13.0.1'
  pod 'ReactiveSwift', :git => 'https://github.com/ReactiveCocoa/ReactiveSwift'
end

def required_pods
  pod 'ObjectMapper', '~> 3.5' #, :git => 'https://github.com/Hearst-DD/ObjectMapper'
  pod 'Moya', '~> 13.0.1' #, :git => 'https://github.com/Moya/Moya'
end

# Test Libraries
def test_pods
  pod 'Quick'
  pod 'Nimble'
  pod 'OHHTTPStubs'
end

target 'Demo' do
  platform :ios, '9.0'
  required_pods
  libraries
end

target 'Demo-RxSwift' do
  platform :ios, '9.0'
  required_pods
  libraries
  libraries_rx_swift
end
